-- 처음에 이 방식을 이용하려고 했으나, 우유와 요거트를 여러개 살 수 있다는 문제점을 발견함.
SELECT IF(COUNT(A.CART_ID)=2,A.CART_ID,NULL) AS 'CART_ID'
FROM (SELECT * FROM CART_PRODUCTS WHERE NAME = 'MILK' OR NAME = 'YOGURT') AS A
GROUP BY A.CART_ID
ORDER BY A.CART_ID ASC;

-- 우유가 담긴 CART_ID를 모두 뽑고, 요거트가 담긴 CART_ID를 모두 뽑아서 INNER JOIN으로 해결
SELECT A.CART_ID
FROM (SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS WHERE NAME = 'MILK') AS A
JOIN (SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS WHERE NAME = 'YOGURT') AS B
ON A.CART_ID = B.CART_ID
ORDER BY A.CART_ID ASC;