SELECT COUNT(*) AS 'count'
FROM (
SELECT NAME FROM ANIMAL_INS  GROUP BY NAME HAVING NAME IS NOT NULL) A;

-- DISTINCT 사용해서 문제 간단하게 해결하기
SELECT COUNT(DISTINCT(NAME)) AS 'count'
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;