SELECT ANIMAL_ID, NAME, IF((SEX_UPON_INTAKE LIKE '%NEUTERED%' OR SEX_UPON_INTAKE LIKE '%SPAYED%'), 'O', 'X') AS '중성화'
FROM ANIMAL_INS;


-- 정규식으로 쓴다면 다음과 같이도 나타낼 수 있음.
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE REGEXP 'NEUTERED|SPAYED', 'O', 'X') AS '중성화'
FROM ANIMAL_INS;