SELECT HOUR(DATETIME) AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME) 
HAVING (HOUR >= 9 AND HOUR <=19)
ORDER BY HOUR(DATETIME) ASC;

-- WHERE절로도 해결할 수 있는데 읽는 순서가 FROM>WHERE>GROUP BY이기 때문에 WHERE 절에서는 HOUR를 쓸 수 없다.
SELECT HOUR(DATETIME) AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM ANIMAL_OUTS 
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC;